const json = {
    "weatherIcon": {
        "阳光明媚": "CLEAR_DAYs",
        "晴朗无云": "CLEAR_DAYs",
        "晴朗": "CLEAR_DAYs",
        "繁星点点": "CLEAR_NIGHT",
        "局部多云": "PARTLY_CLOUDY_DAY",
        "多云": "PARTLY_CLOUDY_DAY",
        "大部晴朗": "PARTLY_CLOUDY_DAY",
        "大部多云": "PARTLY_CLOUDY_DAY",
        "雷阵雨": "IsolatedThundershowers",
        "冰雹": "MixedSnowAndSleet",
        "细雨": "LIGHT_RAIN",
        "有雨": "LIGHT_RAIN",
        "阵雨": "LIGHT_RAIN",
        "局部雷暴雨": "LIGHT_RAIN",
        "局部阵雨": "LIGHT_RAIN",
        "雨夹冰雹": "FREEZING_RAIN",
        "雨": "MODERATE_RAIN",
        "烟雾": "LIGHT_HAZE",
        "有烟雾": "LIGHT_HAZE",
        "有霾": "LIGHT_HAZE",
        "雾霾": "LIGHT_HAZE",
        "阴霾": "LIGHT_HAZE",
        "薄雾": "LIGHT_HAZE",
        "有雾": "LIGHT_HAZE",
        "大雾": "LIGHT_HAZE",
        "零星阵雪": "SNOW",
        "雨雪交加": "SNOW",
        "小阵雪": "SNOW",
        "有雪": "SNOW",
        "大雪": "SNOW",
        "暴雪": "SNOW",
        "雪": "SNOW",
        "刮风": "WIND",
        "有风": "WIND",
    },
    "weatherSF": {
        "阳光明媚": "sun.max.fill",
        "晴朗": "sun.max.fill",
        "晴朗无云": "sun.max.fill",
        "繁星点点": "moon.stars.fill",
        "局部多云": "cloud.fill",
        "多云": "cloud.fill",
        "大部晴朗": "cloud.fill",
        "大部多云": "cloud.fill",
        "雷阵雨": "cloud.drizzle.fill",
        "冰雹": "cloud.drizzle.fill",
        "细雨": "cloud.drizzle.fill",
        "有雨": "cloud.rain.fill",
        "阵雨": "cloud.drizzle.fill",
        "局部阵雨": "cloud.drizzle.fill",
        "局部雷暴雨": "cloud.drizzle.fill",
        "雨夹冰雹": "cloud.drizzle.fill",
        "雨": "cloud.drizzle.fill",
        "烟雾": "sun.haze.fill",
        "有霾": "sun.haze.fill",
        "雾霾": "sun.haze.fill",
        "阴霾": "sun.haze.fill",
        "薄雾": "sun.haze.fill",
        "有雾": "sun.haze.fill",
        "大雾": "sun.haze.fill",
        "零星阵雪": "cloud.snow.fill",
        "雨雪交加": "cloud.snow.fill",
        "小阵雪": "cloud.snow.fill",
        "有雪": "cloud.snow.fill",
        "大雪": "cloud.snow.fill",
        "暴雪": "cloud.snow.fill",
        "雪": "cloud.snow.fill",
        "刮风": "wind",
        "有风": "wind",
    },
}

const weatherInfo = () => {
    return json;
}

module.exports = weatherInfo;