name: "问题反馈"
description: 问题反馈
title: "[BUG]"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告，请**务必确认您的issue不是重复的且不是因为版本问题**

  - type: checkboxes
    attributes:
      label: 您必须确认以下所有内容
      description: |
        您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
      options:
        - label: |
            我已经阅读了脚本开头的注释。
        - label: |
            我确定没有重复的issue。
        - label: |
            我确定是脚本的问题，而不是其他原因（例如，```网络```，```操作```等）。
        - label: |
            我确定这个问题在最新版本中没有被修复。

  - type: input
    id: version
    attributes:
      label: 版本
      description: |
        您使用的是哪个版本的脚本？请填写具体的版本号。
      placeholder: v1.xx.xx
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: |
        请复制粘贴错误日志。
