#!/usr/bin/env bash
targetPath="/Users/lowking/Desktop/Scripts"

# 执行min
uglifyjs $targetPath/util/ToolKit.js -o $targetPath/util/ToolKit.min.js

# 复制min文件内容
pbcopy < $targetPath/util/ToolKit.min.js

# 从剪辑版复制内容
pasteStr=$(pbpaste -Prefer text)

# 替换到所有脚本//ToolKit-start和//ToolKit-end之间的内容
echo "批量替换.js中ToolKit开始"
while IFS= read -r -d '' i
do
	lineno=$(grep -n "//ToolKit-start" "$i")
	if [ -n "$lineno" ]; then
		array=()
		IFS=":" read -r -a array <<< "$lineno"
		lineno=$(( array[0] + 1 ))
		if [ $lineno -ge 1 ]; then
		    sed -i '' $lineno"G" "$i"
		    sed -i '' $lineno"d" "$i"
		    sed -i '' "$(( lineno - 1)) r $targetPath/util/ToolKit.min.js" "$i"
		    printf "%-20s %s\n" "替换行:$lineno" "$i"
		fi
	fi
done < <(find $targetPath -name '*.js' -print0 ! -path '*node_modules')
echo "批量替换.js中ToolKit完成"

