#!/usr/bin/env bash
targetPath="/Users/lowking/Desktop/Scripts"

# 执行min
uglifyjs $targetPath/Scriptable/ScriptableToolKit.js -m -o $targetPath/Scriptable/ScriptableToolKit.min.js

# 复制min文件内容
pbcopy < $targetPath/Scriptable/ScriptableToolKit.min.js

# 从剪辑版复制内容
pasteStr=`pbpaste -Prefer text`

# 替换到所有脚本//ScriptableToolKit-start和//ScriptableToolKit-end之间的内容
echo "批量替换.js中ScriptableToolKit开始"
for i in `find $targetPath -name '*.js' ! -path '*node_modules*'`
do
	lineno=`grep -n "//ScriptableToolKit-start" $i`
	if [ -n "$lineno" ]; then
		array=(`echo $lineno | tr ':' ' '` )
		lineno=$[ ${array[0]} + 0 ]
		if [ $lineno -ge 1 ]; then
			# 调用py
			python ~/bin/replaceAllJs.py $lineno $i $targetPath/Scriptable/ScriptableToolKit.min.js
			echo "$i 已替换【${lineno}】"
		fi
	fi
done
echo "批量替换.js中ScriptableToolKit完成"

