name: Close inactive issues
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: ${{ secrets.DBIS }}
          days-before-issue-close: ${{ secrets.DBIC }}
          stale-issue-label: "stale"
          stale-issue-message: |
            ci: This issue is stale because it has been open for ${{ secrets.DBIS }} days with no activity.
          close-issue-message: |
            ci: This issue was closed because it has been inactive for ${{ secrets.DBIC }} days since being marked as stale.
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.TOKEN }}
